### ISSUE TITLE
Finds no sites.

### ISSUE THREAD

**Issue by RichardLitt** [jlengstorf/ntl-focal-migrate#2]
Tried running this without success: 

```
➜  log git:(master) ✗ npx ntl-focal-migrate --list --account "richard-littauer"

 ntl-focal-migrate  v0.0.1 by Jason Lengstorf
Find all your sites that don’t use the new Focal build image and migrate them.

[]
```

**Comment by jlengstorf** [comment]
@RichardLitt I believe you need to pass in the name, not the slug. Making a guess at yours:

```shell
npx ntl-focal-migrate --list --account "Richard Littauer"
```

Let me know if that doesn't work!

**Comment by RichardLitt** [comment]
Alas, nope. 

```
➜  ~ npx ntl-focal-migrate --list --account "Richard Littauer"
Need to install the following packages:
  ntl-focal-migrate@0.0.1
Ok to proceed? (y) y
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

 ntl-focal-migrate  v0.0.1 by Jason Lengstorf
Find all your sites that don’t use the new Focal build image and migrate them.

[]
```

**Comment by jlengstorf** [comment]
hmm. so, a couple things to check:

1. Is the account name correct? It should be the one that shows up here under your team settings:
    <img width="1171" alt="Screenshot 2022-12-07 at 18 16 21" src="https://user-images.githubusercontent.com/163561/206340300-fa7382c3-2dbc-45a8-91f1-56899dcb9e3c.png">
2. Are there for sure sites that are on the old build image? The tool only lists sites that need to be migrated.
    

I just confirmed that on my personal team, I don't have any sites that need to be migrated and I get an empty array back.

On a different team that's got out-of-date sites, I do get sites back.

Let me know. Thanks!

**Comment by RichardLitt** [comment]
Strange! That name was different: "Richard Littauer's team". But it worked. Thank you!

**Comment by kevinadhiguna** [comment]
I faced the same issue and followed steps above, but somehow it still returned an empty array.

`netlify status` : 
```
❯ netlify status                                               
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  kevin
Email: kevinsemail@email.net
Teams: 
  kevinadhiguna’s team: Collaborator
 ›   Warning: Did you run `netlify link` yet?
 ›   Error: You don't appear to be in a folder that is linked to a site
```

`npx ntl-focal-migrate --list --account "kevin"` :
```
❯ npx ntl-focal-migrate --list --account "kevin"

 ntl-focal-migrate  v0.0.1 by Jason Lengstorf
Find all your sites that don’t use the new Focal build image and migrate them.

[]
```

`npx ntl-focal-migrate --list --account "kevinadhiguna’s team"` :
```
❯ npx ntl-focal-migrate --list --account "kevinadhiguna’s team"

 ntl-focal-migrate  v0.0.1 by Jason Lengstorf
Find all your sites that don’t use the new Focal build image and migrate them.

[]
```

<hr/>

I see some projects are still using the old build image, so they should be listed :

![netlify-problem](https://user-images.githubusercontent.com/43397636/219552941-9fe0eaeb-da40-49fe-8dde-30a06babb200.png)

Also, the team name is already correct, I guess : 

![netlify-problem-2](https://user-images.githubusercontent.com/43397636/219553182-49b56752-f3f5-4159-9cb4-93a7c9749e4b.png)

Any help is appreciated!

**Comment by kevinadhiguna** [comment]
Here's my two cents : 

If it returns an empty array but team name is correct, try to check [Netlify Status](https://www.netlifystatus.com/) in case Netlify service/API is down. If so, it's better to try again later after the service is up again.
